#!/bin/bash

#    libsdldx-config a helper script for finding the libs and cflags
#    Copyright (C) 2004 sdldx team<sdldx@freshx.de>
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    SDLDX is a wrapper, which provides DirectX functionality on top of the
#    Simple Direct Media Layer (SDL) library. Using SDLDX enables you to easily
#    port DirectX applications (for example games) to any platform supported
#    by the SDL library.

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no
name="sdldx"
version="not yet released"

# get all what sdl-config knows:

sdl_config=`which sdl-config`
sdl_cflags=`$sdl_config --cflags`
sdl_libs=`$sdl_config --libs`
sdl_static_libs=`$sdl_config --static-libs`

# get all what we should know about gtk2

gtk_config=`which pkg-config`
gtk_cflags=`$gtk_config --cflags gtk+-2.0`
gtk_libs=`$gtk_config --libs gtk+-2.0`
gtk_static_libs=`$gtk_config --libs gtk+-2.0`

usage="\
Usage: $0 [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --prefix)
      echo $prefix
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo "$name - $version"
      ;;
    --cflags)
      echo $sdl_cflags $gtk_cflags -O3 -I${prefix}/include/$name/
      ;;
    --libs)
      libdirs="-L${exec_prefix}/lib -Wl,-rpath,${exec_prefix}/lib"
      echo $sdl_libs $gtk_libs $libdirs -l$name
      ;;
    --static-libs)
      libdirs="-L${exec_prefix}/lib -Wl,-static,-rpath,${exec_prefix}/lib"
      echo $sdl_static_libs $gtk_static_libs $libdirs -l$name
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
